# Generated by Django 6.1.2 on 2026-10-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_code_reinitialisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profils/', verbose_name='photo de profil'),
        ),
    ]
