# Generated by Django 6.1.2 on 2026-10-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0005_utilisateur_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='type_utilisateur',
            field=models.CharField(choices=[('AGRICULTEUR', 'Agriculteur'), ('DETENTEUR', 'Propriétaire de machine')], default='AGRICULTEUR', max_length=20, verbose_name="type d'utilisateur"),
        ),
    ]
