# Generated by Django 6.1.2 on 2026-10-08 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0006_libelle_proprietaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeChangementTelephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hache', models.CharField(max_length=128)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('essais', models.PositiveSmallIntegerField(default=0)),
                ('nouveau_telephone', models.CharField(max_length=20)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='code_changement_telephone', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'code de changement de téléphone',
            },
        ),
    ]
