"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlsplit

from corsheaders.defaults import default_headers
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


def _env(nom, defaut=''):
    """Variable d'environnement (ou de .env) ; vide ou absente = valeur par défaut."""
    return os.environ.get(nom) or defaut


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# Production par défaut : le mode développement se demande explicitement (DJANGO_DEBUG=True dans .env).
DEBUG = _env('DJANGO_DEBUG', 'False') == 'True'

# Hors développement, pas de clé par défaut : le serveur refuse de démarrer sans DJANGO_SECRET_KEY.
SECRET_KEY = _env('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured(
            'DJANGO_SECRET_KEY manquante. Générez-en une : '
            'python -c "import secrets; print(secrets.token_urlsafe(50))"'
        )
    SECRET_KEY = 'django-insecure-cle-de-developpement-uniquement'

ALLOWED_HOSTS = _env('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'comptes',
    'machines',
    'reservations',
    'offres',
]

AUTH_USER_MODEL = 'comptes.Utilisateur'

# Nom d'utilisateur, e-mail ou numéro de téléphone.
AUTHENTICATION_BACKENDS = ['comptes.backends.IdentifiantBackend']

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Fichiers statiques (admin) servis par l'application elle-même, sans serveur web devant.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Avant CommonMiddleware : répond aux requêtes du site React servi sur une autre adresse (VITE_API_URL).
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

def _base_depuis_url(url):
    """postgresql://utilisateur:mot-de-passe@serveur:5432/base?sslmode=require (format des hébergeurs)."""
    adresse = urlsplit(url)
    if adresse.scheme not in ('postgres', 'postgresql'):
        raise ImproperlyConfigured('DATABASE_URL doit commencer par postgresql:// (ou postgres://).')
    return {
        'NAME': unquote(adresse.path.lstrip('/')),
        'USER': unquote(adresse.username or ''),
        'PASSWORD': unquote(adresse.password or ''),
        'HOST': adresse.hostname or '',
        'PORT': str(adresse.port or 5432),
        'SSLMODE': parse_qs(adresse.query).get('sslmode', [''])[0],
    }


# DATABASE_URL (adresse complète fournie par l'hébergeur) est prioritaire ; sinon les variables DB_*.
_base = _base_depuis_url(_env('DATABASE_URL')) if _env('DATABASE_URL') else {
    'NAME': _env('DB_NAME', 'agrinyo'),
    'USER': _env('DB_USER', 'postgres'),
    'PASSWORD': _env('DB_PASSWORD'),
    'HOST': _env('DB_HOST', 'localhost'),
    'PORT': _env('DB_PORT', '5432'),
    'SSLMODE': '',
}
# Chiffrement de la connexion, souvent exigé par les bases hébergées : DB_SSLMODE=require.
_sslmode_url = _base.pop('SSLMODE')
_sslmode = _env('DB_SSLMODE', _sslmode_url)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        **_base,
        # Connexions réutilisées entre les requêtes (secondes) ; 0 = une connexion par requête.
        'CONN_MAX_AGE': int(_env('DB_CONN_MAX_AGE', '60')),
        'CONN_HEALTH_CHECKS': True,
        'OPTIONS': {'sslmode': _sslmode} if _sslmode else {},
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'Africa/Lome'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
# Rempli par « collectstatic » (image Docker) et servi par WhiteNoise.
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'
# Photos envoyées servies par Django hors développement (image Docker) : aucun serveur web dédié devant.
SERVIR_MEDIA = DEBUG or _env('DJANGO_SERVIR_MEDIA') == 'True'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Cookie de session du site : invisible pour le JavaScript, HTTPS obligatoire hors développement.
SESSION_COOKIE_HTTPONLY = True
# Lax : site et API sur le même domaine ou des sous-domaines (app.agrilink.tg / api.agrilink.tg).
# None : site et API sur deux domaines sans rapport (ex. hébergeurs différents) ; exige HTTPS.
SESSION_COOKIE_SAMESITE = CSRF_COOKIE_SAMESITE = _env('DJANGO_COOKIES_SAMESITE', 'Lax')
# DJANGO_SECURE_COOKIES=False seulement pour un essai en HTTP sans DEBUG (ex. image Docker en local).
_COOKIES_SECURISES = _env('DJANGO_SECURE_COOKIES', str(not DEBUG)) == 'True'
SESSION_COOKIE_SECURE = _COOKIES_SECURISES
CSRF_COOKIE_SECURE = _COOKIES_SECURISES
# Domaine parent (ex. .agrilink.tg) : le cookie CSRF devient lisible par le site sur un sous-domaine voisin.
# Vide : le site demande le jeton à /api/csrf/ (marche aussi entre domaines sans rapport).
CSRF_COOKIE_DOMAIN = _env('DJANGO_CSRF_COOKIE_DOMAIN') or None

# HTTPS terminé par un proxy ou l'hébergeur (Caddy, Render, Railway…) : DJANGO_HTTPS=True.
# Le proxy écrase l'en-tête X-Forwarded-Proto ; Django s'y fie pour savoir que la requête est en HTTPS.
if _env('DJANGO_HTTPS') == 'True' or SESSION_COOKIE_SAMESITE == 'None':
    # SameSite=None n'est accepté par les navigateurs que sur des cookies Secure.
    SESSION_COOKIE_SECURE = CSRF_COOKIE_SECURE = True
if _env('DJANGO_HTTPS') == 'True':
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # HSTS : le navigateur n'essaie plus jamais le HTTP. Commencer court (ex. 3600) puis passer à un an.
    SECURE_HSTS_SECONDS = int(_env('DJANGO_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = _env('DJANGO_HSTS_SOUS_DOMAINES', 'False') == 'True'
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'
# Adresses du site React quand il n'est pas servi par l'API elle-même (frontend/.env : VITE_API_URL),
# ex. https://app.agrilink.tg, séparées par des virgules. En développement : Vite (5173) et l'image frontend (3000).
_ORIGINES_DEV = ['http://localhost:5173', 'http://localhost:3000'] if DEBUG else []
ORIGINES_SITE = _ORIGINES_DEV + [o for o in _env('DJANGO_CSRF_TRUSTED_ORIGINS').split(',') if o]
CSRF_TRUSTED_ORIGINS = ORIGINES_SITE
# Le site peut appeler l'API et envoyer le cookie de session ; les autres origines sont refusées par le navigateur.
CORS_ALLOWED_ORIGINS = ORIGINES_SITE
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = (*default_headers, 'x-agrilink-client')

REST_FRAMEWORK = {
    # Flutter : jeton dans l'en-tête « Authorization: Token … ».
    # Site React : cookie de session HttpOnly + CSRF, aucun jeton lisible par le JavaScript.
    # Token en premier : une requête sans identification reçoit 401 (et non 403).
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.IsAuthenticatedOrReadOnly'],
    # Derrière un proxy ou un hébergeur : 1, pour limiter les essais par adresse du client et non par celle
    # du proxy. Sans proxy devant gunicorn : ne pas définir.
    'NUM_PROXIES': int(_env('DJANGO_NUM_PROXIES')) if _env('DJANGO_NUM_PROXIES') else None,
    'DEFAULT_THROTTLE_RATES': {
        # Freine les essais de mots de passe en série.
        'connexion': _env('THROTTLE_CONNEXION', '10/min'),
        'inscription': _env('THROTTLE_INSCRIPTION', '5/min'),
        # Chaque demande peut coûter un SMS.
        'mot_de_passe_oublie': _env('THROTTLE_MOT_DE_PASSE_OUBLIE', '10/hour'),
        'reinitialisation': _env('THROTTLE_REINITIALISATION', '10/min'),
        'changement_mot_de_passe': _env('THROTTLE_CHANGEMENT_MOT_DE_PASSE', '10/min'),
        'changement_telephone': _env('THROTTLE_CHANGEMENT_TELEPHONE', '10/hour'),
        # Messagerie : freine les envois en rafale.
        'messages': _env('THROTTLE_MESSAGES', '30/min'),
        # Offres lancées et propositions envoyées.
        'offres': _env('THROTTLE_OFFRES', '20/hour'),
    },
}

# SMS (codes « mot de passe oublié ») : « console » écrit le SMS dans le terminal de runserver,
# « twilio » l'envoie vraiment. Voir comptes/sms.py.
SMS_BACKEND = _env('SMS_BACKEND', 'console')
TWILIO_ACCOUNT_SID = _env('TWILIO_ACCOUNT_SID')
TWILIO_AUTH_TOKEN = _env('TWILIO_AUTH_TOKEN')
TWILIO_FROM = _env('TWILIO_FROM')


# Journaux sur la sortie standard (docker logs) : sans cela, hors DEBUG, une erreur 500 ne laisse aucune trace.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {'simple': {'format': '{asctime} {levelname} {name} : {message}', 'style': '{'}},
    'handlers': {'console': {'class': 'logging.StreamHandler', 'formatter': 'simple'}},
    'root': {'handlers': ['console'], 'level': _env('DJANGO_LOG_LEVEL', 'INFO')},
    'loggers': {
        'django': {'handlers': ['console'], 'level': _env('DJANGO_LOG_LEVEL', 'INFO'), 'propagate': False},
    },
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# Aucun e-mail envoyé par l'application pour l'instant (les codes partent par SMS).
MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend' if DEBUG
        else 'django.core.mail.backends.smtp.EmailBackend',
    },
}
