# Generated by Django 6.1.2 on 2026-10-07 17:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('type_machine', models.CharField(choices=[('TRACTEUR', 'Tracteur'), ('MOTOCULTEUR', 'Motoculteur'), ('MOISSONNEUSE', 'Moissonneuse'), ('BATTEUSE', 'Batteuse'), ('DECORTIQUEUSE', 'Décortiqueuse'), ('PULVERISATEUR', 'Pulvérisateur'), ('SEMOIR', 'Semoir'), ('CHARRUE', 'Charrue'), ('MOTOPOMPE', 'Motopompe')], max_length=20, verbose_name='type de machine')),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='machines/')),
                ('prix', models.PositiveIntegerField(verbose_name='prix (FCFA)')),
                ('unite_prix', models.CharField(choices=[('JOUR', 'jour'), ('HEURE', 'heure'), ('HECTARE', 'hectare')], default='JOUR', max_length=10, verbose_name='unité de prix')),
                ('zone', models.CharField(choices=[('MARITIME', 'Maritime'), ('PLATEAUX', 'Plateaux'), ('CENTRALE', 'Centrale'), ('KARA', 'Kara'), ('SAVANES', 'Savanes')], max_length=20)),
                ('localisation', models.CharField(max_length=100, verbose_name='ville / localité')),
                ('disponible', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='machines.machine')),
            ],
            options={
                'verbose_name_plural': 'avis',
                'ordering': ['-date_creation'],
                'constraints': [models.UniqueConstraint(fields=('machine', 'auteur'), name='un_avis_par_auteur_et_machine')],
            },
        ),
    ]
