# Generated by Django 6.1.2 on 2026-10-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='credit_photo',
            field=models.CharField(blank=True, max_length=200, verbose_name='crédit photo'),
        ),
    ]
