# Generated by Django 6.1.2 on 2026-10-07 17:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0002_machine_credit_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='date de début')),
                ('date_fin', models.DateField(verbose_name='date de fin')),
                ('quantite', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.5'))])),
                ('prix_unitaire', models.PositiveIntegerField(verbose_name='prix unitaire (FCFA)')),
                ('unite_prix', models.CharField(choices=[('JOUR', 'jour'), ('HEURE', 'heure'), ('HECTARE', 'hectare')], max_length=10)),
                ('montant_estime', models.PositiveIntegerField(verbose_name='montant estimé (FCFA)')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_reponse', models.DateTimeField(blank=True, null=True, verbose_name='date de réponse')),
                ('agriculteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='machines.machine')),
            ],
            options={
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['machine', 'statut', 'date_debut'], name='reservation_machine_98b709_idx')],
            },
        ),
    ]
