# Generated by Django 6.1.2 on 2026-10-08 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0002_machine_credit_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_machine', models.CharField(choices=[('TRACTEUR', 'Tracteur'), ('MOTOCULTEUR', 'Motoculteur'), ('MOISSONNEUSE', 'Moissonneuse'), ('BATTEUSE', 'Batteuse'), ('DECORTIQUEUSE', 'Décortiqueuse'), ('PULVERISATEUR', 'Pulvérisateur'), ('SEMOIR', 'Semoir'), ('CHARRUE', 'Charrue'), ('MOTOPOMPE', 'Motopompe')], max_length=20, verbose_name='type de machine')),
                ('description', models.TextField(max_length=1000, verbose_name='besoin')),
                ('zone', models.CharField(choices=[('MARITIME', 'Maritime'), ('PLATEAUX', 'Plateaux'), ('CENTRALE', 'Centrale'), ('KARA', 'Kara'), ('SAVANES', 'Savanes')], max_length=20)),
                ('localisation', models.CharField(max_length=100, verbose_name='ville / localité')),
                ('date_souhaitee', models.DateField(blank=True, null=True, verbose_name='date souhaitée')),
                ('budget', models.PositiveIntegerField(blank=True, null=True, verbose_name='budget (FCFA)')),
                ('unite_budget', models.CharField(choices=[('JOUR', 'jour'), ('HEURE', 'heure'), ('HECTARE', 'hectare')], default='JOUR', max_length=10, verbose_name='unité du budget')),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('FERMEE', 'Fermée')], default='OUVERTE', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('agriculteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=500)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('vue_le', models.DateTimeField(blank=True, null=True, verbose_name='vue le')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions', to='machines.machine')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions', to='offres.offre')),
            ],
            options={
                'ordering': ['date_creation', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='offre',
            index=models.Index(fields=['statut', 'zone', 'type_machine'], name='offres_offr_statut_e6617d_idx'),
        ),
        migrations.AddConstraint(
            model_name='proposition',
            constraint=models.UniqueConstraint(fields=('offre', 'machine'), name='une_proposition_par_machine_et_offre'),
        ),
    ]
